In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import streamlit as st
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
import pickle
from pyprojroot import here

In [14]:
patientNum = 1

In [15]:
Xy = pd.read_csv(here() / 'data/filtered05/Xy_2020_06_11_1916.csv')
y1 = Xy[Xy['label']==1]
y1 = y1.iloc[0:4]

In [16]:
y0 = Xy[Xy['label']==0]
y0 = y0.iloc[0:4]

In [17]:
Xy_patients = pd.concat([y0, y1])
Xy_patients

,patientunitstayid,label,age,admissionweight,admissionheight,bmi,gender_Female,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,...,immunosuppression,cirrhosis,activetx,ima,midur,oobventday1,oobintubday1,diabetes,visitnumber,heartrate
0,141168,0,70,84.30,152.4,36.295906,1,0,0,1,...,0,0,1,0,0,0,0,0,1,125.052830
1,141194,0,68,73.90,180.3,22.732803,0,0,0,1,...,0,0,0,0,0,0,0,1,1,86.860627
2,141197,0,71,102.10,162.6,38.617545,0,0,0,1,...,0,0,0,0,0,0,0,0,1,97.307692
3,141203,0,77,70.20,160.0,27.421875,1,0,0,1,...,0,0,1,0,0,1,0,1,1,91.543554
177,143466,1,60,76.70,170.0,26.539792,1,0,0,1,...,1,0,1,0,0,1,1,1,1,82.696864
289,144689,1,57,49.89,170.2,17.222429,0,0,0,1,...,0,0,0,0,0,0,0,0,1,94.446215
1059,153993,1,59,68.30,167.6,24.314910,1,0,0,1,...,0,0,0,0,0,0,0,0,1,109.660839
1070,154134,1,56,69.40,180.0,21.419753,0,0,0,1,...,0,0,0,0,0,0,0,0,1,115.417625

In [18]:
Xy_patients.reindex()
Xy_patients.head()

,patientunitstayid,label,age,admissionweight,admissionheight,bmi,gender_Female,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,...,immunosuppression,cirrhosis,activetx,ima,midur,oobventday1,oobintubday1,diabetes,visitnumber,heartrate
0,141168,0,70,84.3,152.4,36.295906,1,0,0,1,...,0,0,1,0,0,0,0,0,1,125.052830
1,141194,0,68,73.9,180.3,22.732803,0,0,0,1,...,0,0,0,0,0,0,0,1,1,86.860627
2,141197,0,71,102.1,162.6,38.617545,0,0,0,1,...,0,0,0,0,0,0,0,0,1,97.307692
3,141203,0,77,70.2,160.0,27.421875,1,0,0,1,...,0,0,1,0,0,1,0,1,1,91.543554
177,143466,1,60,76.7,170.0,26.539792,1,0,0,1,...,1,0,1,0,0,1,1,1,1,82.696864

In [ ]:
for i in range(0, Xy_patients.shape[0]):
    Xy_patient = Xy_patients.iloc[i]
    Xy_patient.loc[i, 'patientunitstayid'] = i

In [26]:
X_patient = pd.read_csv(here() / 'Patient1.csv')

In [27]:
X_patient

,age,admissionweight,admissionheight,bmi,gender_Female,ethnicity_African American,ethnicity_Asian,ethnicity_Caucasian,ethnicity_Hispanic,ethnicity_Native American,...,immunosuppression,cirrhosis,activetx,ima,midur,oobventday1,oobintubday1,diabetes,visitnumber,heartrate
0,70,84.3,152.4,36.295906,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,125.05283

In [37]:
X_patient.iloc[0]['age']

70.0

In [20]:
model_name_pickle_read = (here() / 'models/model_2020_06_11_2128.pickle')
scaler_name_pickle_read = (here() / 'models/scaler_2020_06_11_2128.pickle')

clf = pickle.load(open(model_name_pickle_read, 'rb'))
scaler = pickle.load(open(scaler_name_pickle_read, 'rb'))

In [21]:
X_test_sc = scaler.transform(X_patient)
y_probs = clf.predict_proba(X_test_sc)[:,1]

In [22]:
y_probs

array([0.00558589])